--- #YAML:1.0
name:               XML-LibXSLT-Easy
version:            0.03
abstract:           ~
author:  []
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Config::Any:          0
    Devel::PartialDump:   0
    File::Glob:           0
    Moose:                0.50
    MooseX::MultiMethods:  0
    MooseX::Types:        0
    MooseX::Types::Moose:  0
    MooseX::Types::Path::Class:  0
    MooseX::Types::URI:   0
    namespace::clean:     0.08
    Path::Class:          0
    Scope::Guard:         0
    Test::Exception:      0
    Test::More:           0
    Test::use::ok:        0
    Test::XML:            0
    URI:                  0
    XML::LibXML:          0
    XML::LibXSLT:         0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
