--- #YAML:1.0
name:                XML-LibXSLT-Easy
version:             0.01
abstract:            ~
license:             ~
author:              ~
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Devel::PartialDump:            0
    Moose:                         0
    MooseX::Types::Moose:          0
    MooseX::Types::Path::Class:    0
    MooseX::Types::URI:            0
    MooseX::Types::VariantTable:   0
    namespace::clean:              0.08
    Path::Class:                   0
    Test::use::ok:                 0
    Test::XML:                     0
    XML::LibXML:                   0
    XML::LibXSLT:                  0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
